#############################################################################
# Makefile for building: sqldrivers
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  sqldrivers.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile sqldrivers.pro -- PSQL_INCDIR=/usr/include/postgresql
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sqldrivers1.0.0
DISTDIR = /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/.obj/sqldrivers1.0.0
SUBTARGETS    =  \
		sub-psql \
		sub-sqlite


sub-psql-qmake_all:  FORCE
	@test -d psql/ || mkdir -p psql/
	cd psql/ && $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro
	cd psql/ && $(MAKE) -f Makefile qmake_all
sub-psql: FORCE
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile
sub-psql-make_first: FORCE
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile 
sub-psql-all: FORCE
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile all
sub-psql-clean: FORCE
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile clean
sub-psql-distclean: FORCE
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile distclean
sub-psql-install_subtargets: FORCE
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile install
sub-psql-uninstall_subtargets: FORCE
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile uninstall
sub-sqlite-qmake_all:  FORCE
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro
	cd sqlite/ && $(MAKE) -f Makefile qmake_all
sub-sqlite: FORCE
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile
sub-sqlite-make_first: FORCE
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile 
sub-sqlite-all: FORCE
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile all
sub-sqlite-clean: FORCE
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile clean
sub-sqlite-distclean: FORCE
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile distclean
sub-sqlite-install_subtargets: FORCE
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile install
sub-sqlite-uninstall_subtargets: FORCE
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile uninstall

Makefile: sqldrivers.pro .qmake.conf /home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/linux-g++/qmake.conf /home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/spec_pre.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/unix.conf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/linux.conf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/sanitize.conf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/gcc-base.conf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/g++-base.conf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/g++-unix.conf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/qconfig.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_functions.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_config.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/spec_post.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/qmodule.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_build_config.prf \
		/home/kofr/dev/tools/5.9.5/Src/qtbase/.qmake.conf \
		.qmake.conf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/toolchain.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/default_pre.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/configure_base.prf \
		configure.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_configure.prf \
		qtsqldrivers-config.pri \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/resolve_config.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/default_post.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/exceptions_off.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_example_installs.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_docs_targets.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/precompile_header.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/unix/largefile.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/warn_on.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qmake_use.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/file_copies.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_build_extra.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/yacc.prf \
		/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/lex.prf \
		sqldrivers.pro
	$(QMAKE) -o Makefile sqldrivers.pro -- PSQL_INCDIR=/usr/include/postgresql
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/spec_pre.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/unix.conf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/linux.conf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/sanitize.conf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/gcc-base.conf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/g++-base.conf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/common/g++-unix.conf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/qconfig.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_functions.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_config.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/spec_post.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/qmodule.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_build_config.prf:
/home/kofr/dev/tools/5.9.5/Src/qtbase/.qmake.conf:
.qmake.conf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/toolchain.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/default_pre.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/configure_base.prf:
configure.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_configure.prf:
qtsqldrivers-config.pri:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/resolve_config.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/default_post.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/exceptions_off.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_example_installs.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_docs_targets.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/precompile_header.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/unix/largefile.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/warn_on.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qmake_use.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/file_copies.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/qt_build_extra.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/testcase_targets.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/yacc.prf:
/home/kofr/dev/tools/5.12.0/gcc_64/mkspecs/features/lex.prf:
sqldrivers.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile sqldrivers.pro -- PSQL_INCDIR=/usr/include/postgresql

qmake_all: sub-psql-qmake_all sub-sqlite-qmake_all FORCE

make_first: sub-psql-make_first sub-sqlite-make_first  FORCE
all: sub-psql-all sub-sqlite-all  FORCE
clean: sub-psql-clean sub-sqlite-clean  FORCE
distclean: sub-psql-distclean sub-sqlite-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-psql-install_subtargets sub-sqlite-install_subtargets FORCE
uninstall_subtargets: sub-psql-uninstall_subtargets sub-sqlite-uninstall_subtargets FORCE

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

sub-psql-install_html_docs:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile install_html_docs
sub-sqlite-install_html_docs:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile install_html_docs
install_html_docs: sub-psql-install_html_docs sub-sqlite-install_html_docs

sub-psql-uninstall_html_docs:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile uninstall_html_docs
sub-sqlite-uninstall_html_docs:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile uninstall_html_docs
uninstall_html_docs: sub-psql-uninstall_html_docs sub-sqlite-uninstall_html_docs

sub-psql-install_qch_docs:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile install_qch_docs
sub-sqlite-install_qch_docs:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile install_qch_docs
install_qch_docs: sub-psql-install_qch_docs sub-sqlite-install_qch_docs

sub-psql-uninstall_qch_docs:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile uninstall_qch_docs
sub-sqlite-uninstall_qch_docs:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile uninstall_qch_docs
uninstall_qch_docs: sub-psql-uninstall_qch_docs sub-sqlite-uninstall_qch_docs

sub-psql-install_docs:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile install_docs
sub-sqlite-install_docs:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile install_docs
install_docs: sub-psql-install_docs sub-sqlite-install_docs

sub-psql-uninstall_docs:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile uninstall_docs
sub-sqlite-uninstall_docs:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile uninstall_docs
uninstall_docs: sub-psql-uninstall_docs sub-sqlite-uninstall_docs

sub-psql-qch_docs:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile qch_docs
sub-sqlite-qch_docs:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile qch_docs
qch_docs: sub-psql-qch_docs sub-sqlite-qch_docs

sub-psql-prepare_docs:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile prepare_docs
sub-sqlite-prepare_docs:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile prepare_docs
prepare_docs: sub-psql-prepare_docs sub-sqlite-prepare_docs

sub-psql-generate_docs:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile generate_docs
sub-sqlite-generate_docs:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile generate_docs
generate_docs: sub-psql-generate_docs sub-sqlite-generate_docs

sub-psql-check:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile check
sub-sqlite-check:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile check
check: sub-psql-check sub-sqlite-check

sub-psql-benchmark:
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -f Makefile benchmark
sub-sqlite-benchmark:
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-psql-benchmark sub-sqlite-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-psql-distdir sub-sqlite-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents .qmake.conf configure.pri qtsqldrivers-config.pri sqldrivers.pro $(DISTDIR)/

sub-psql-distdir: FORCE
	@test -d psql/ || mkdir -p psql/
	cd psql/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/psql/psql.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/psql

sub-sqlite-distdir: FORCE
	@test -d sqlite/ || mkdir -p sqlite/
	cd sqlite/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kofr/dev/tools/5.9.5/Src/qtbase/src/plugins/sqldrivers/sqlite/sqlite.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/sqlite

