QT.sqldrivers.enabled_features = 
QT.sqldrivers.disabled_features = 
QT.sqldrivers.QT_CONFIG = 
QT.sqldrivers.exports = 
QT.sqldrivers_private.enabled_features = sql-psql sql-sqlite
QT.sqldrivers_private.disabled_features = sql-db2 sql-ibase sql-mysql sql-oci sql-odbc sql-sqlite2 sql-tds system-sqlite
QT.sqldrivers_private.libraries = psql
QMAKE_LIBS_PSQL = -lpq
QMAKE_INCDIR_PSQL = /usr/include/postgresql
